version: 2
jobs:
  build:
    docker:
      - image: johnnyasantoss/dotnet-mono-docker:dotnet2.0-mono5.2-runtime
    steps:
      - checkout
      - setup_remote_docker
      - run: |          
          ./build.sh
workflows:
  version: 2
  build_push:
    jobs:
      - build:
          filters:
            branches:
              only: master